### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by tim-coder** [roipeker/flutter_translation_sheet#19]
When I install fts using

` flutter pub global activate flutter_translation_sheet`

I get a warning:

`Warning: Executable "fts" runs "bin/main.dart", which was not found in flutter_translation_sheet.`

If I subsequently run` fts run` to create the template, I get:

`No active package flutter_translation_sheet.`

What am I missing?

**Comment by roipeker** [comment]
Sorry for the late reply, I'm currently away. Will check the issue later this week. Thanks for reporting it!

**Comment by roipeker** [comment]
Ok, I checked. New computer, new installation, so I was able to try it fresh; and yes, had the same problem.

Seems like it's an issue with syslinks created by **pub**.

Try to use dart instead of flutter...
`dart pub global activate flutter_translation_sheet`

You might need to add the pub-cache PATH...

```bash
Warning: Pub installs executables into $HOME/.pub-cache/bin, which is not on your path.
You can fix that by adding this to your shell's config file (.bashrc, .bash_profile, etc.):

  export PATH="$PATH":"$HOME/.pub-cache/bin"
```

I'm using **zsh**, so in my case, I edit with VisualCode:

```bash
code  ~/.zshrc
```
Add the PATH... then run:

```bash
source ~/.zshrc
```

You might be able to install and run `fts` properly.

Check the installation with:
`fts --version`

(Forget about the update message you might get... ).

Good luck!
